name: Vercel Preview Deployment

on:
  push:
    branches-ignore:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --yes | tail -1 | tr -d '\n\r')
          echo "Preview deployed to: $DEPLOY_URL"
          echo "DEPLOY_URL=${DEPLOY_URL}" >> $GITHUB_ENV
          echo "url=${DEPLOY_URL}" >> $GITHUB_OUTPUT

      - name: Wait for deployment to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: ${{ steps.deploy.outputs.url }}
          timeout: 300

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests on preview
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=${{ steps.deploy.outputs.url }}
          browser: chrome
        env:
          BASE_URL: ${{ steps.deploy.outputs.url }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DBNAME_SUFFIX: ${{ secrets.MONGODB_DBNAME_SUFFIX }}
          BETTER_AUTH_SESSION_TOKEN: ${{ secrets.BETTER_AUTH_SESSION_TOKEN }}
      
      - name: 'notify vercel'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: 'Vercel - nomnom-notes: preview'